sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "7"
  - "6"
  - "5"
  - "4"
script:
  - yarn test
branches:
  only:
    - master
matrix:
  fast_finish: true

